mnk_mode = true
keybind_a = "Space"
keybind_b = "X"
keybind_x = "G"
keybind_y = "L"
keybind_left_trigger = "Down"
keybind_right_trigger = "Up"
keybind_left_shoulder = "L"
keybind_right_shoulder = "C"
keybind_lstick_up = ""
keybind_lstick_down = ""
keybind_lstick_left = "Left"
keybind_lstick_right = "Right"
keybind_lstick_press = ""
keybind_rstick_press = ""
keybind_dpad_up = "Return"
keybind_dpad_down = "B"
keybind_dpad_left = "M"
keybind_dpad_right = "Tab"
keybind_back = "R"
